### ISSUE TITLE
使用less自定义变量问题

### ISSUE THREAD

**Issue by wangs1203** [GitOfZGT/theme-css-extract-webpack-plugin#9]
如何使用less自定义变量问题？
例如

在theme文件中 
blue-theme.less 定义`@light-primary-color: #EEE;`
green-theme.less 定义`@light-primary-color: #e6f1f0;`

在index.less
```less
.bg-light-primary {
  background: @light-primary-color;
}
```

报错@light-primary-color is undefined
